name: ublue-os-slimmer
description: Lizi's UBlue OS

base-image: ghcr.io/ublue-os/ucore-minimal
image-version: latest

modules:
  - type: remove
    packages:
      - cockpit
      - cockpit-*
      - toolbox

  - type: rpm-ostree
    install:
      - moby-engine
      - docker-compose-plugin
      - tailscale
      - wireguard-tools
      - tmux

  - type: systemd
    enabled:
      - docker.service
      - tailscaled.service
      - zincati.service
