name: liziulone-os
description: Lizi CoreOS (bare minium for my server)

base-image: quay.io/fedora/fedora-coreos:stable
image-version: latest

modules:
  - type: rpm-ostree
    install:
      - moby-engine
      - docker-compose-plugin
      - tailscale
      - wireguard-tools
      - tmux
      - fastfetch

  - type: systemd
    enabled:
      - docker.service
      - docker.socket
      - tailscaled.service
      - zincati.service

  - type: files
    files:
      - path: /etc/modules-load.d/network.conf
        contents: |
          ip_tables
          iptable_filter
          nf_conntrack
          tun
