name: lizi-coreos-server
description: Lizi ServerOS (Optimized for Weekly Monday Updates)

base-image: quay.io/fedora/fedora-coreos
image-version: stable

modules:
  - type: script
    snippets:
      - |
        curl -Lo /etc/yum.repos.d/tailscale.repo https://pkgs.tailscale.com/stable/fedora/tailscale.repo

  - type: rpm-ostree
    install:
      - moby-engine
      - docker-compose
      - tailscale
      - fastfetch

  - type: files
    files:
      - destination: /etc/zincati/config.d/50-maintenance-window.toml
        contents: |
          [updates]
          strategy = "periodic"

          [[updates.periodic.window]]
          days = [ "Mon" ]
          start_time = "03:00"
          length_minutes = 60

  - type: systemd
    system:
      enabled:
        - docker.service
        - tailscaled.service
        - zincati.service

  - type: script
    snippets:
      - |
        ln -sf /usr/share/zoneinfo/Asia/Bangkok /etc/localtime
        echo "Asia/Bangkok" > /etc/timezone
