name: bluebuild

on:
  schedule:
    - cron: "45 19 * * 0"
  push:
    paths-ignore:
      - "**.md"
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  bluebuild:
    name: Build Custom Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    strategy:
      fail-fast: false
      matrix:
        recipe:
          - recipe.yml

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v7

      - name: Clear BuildKit Cache
        run: |
          docker buildx prune -af

      - name: Build Custom Image
        uses: blue-build/github-action@v1.12
        with:
          recipe: ${{ matrix.recipe }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}
          maximize_build_space: true
          build_opts: "--no-sign"
